name: test1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_hooks:
  flutter_riverpod:
  riverpod_annotation:
  supabase_flutter:
  # freezed
  freezed_annotation:

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  riverpod_generator:
  # freezed
  freezed:
  # json形式のレスポンスを受け取るので、変換用に「json_serializable」もインストール
  json_serializable:

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
